services: 
  app:
    build: .
    container_name: whisper-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/whisper-db
      - JWT_SECRET=4c2a57d6d42e73e71312b24ab784eb76424a6a7909dbb9283b052b1c8cf005aa
      - NODE_ENV=development
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: ["node", "dist/server.js"]

  db:
    image: postgres:13-alpine
    container_name: whisper-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whisper-db
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
